#pragma once
#include "Paperback.h"
#include "../../build/Paperback_V2/paperback_pch.h"
#include "Editor/EditorPanels.h"
#include "Editor/EditorPanels_inline.h"
#include <dearImGui/IconsFontAwesome5.h>
#include <dearImGui/imgui.h>
#include "Editor/EditorLogger.h"
#include "Editor/EditorLogger_Inline.h"
